launch_components:
  bebop_autonomy: false
  point_camera_downward: false
  record_rosbag: false
  launch_xbox_controller: false
  launch_arlocros: true
  launch_beswarm: false

bebops:
  bebop_two:
    ros_master_port: '11311'
    bebop_ip: '192.168.42.1'
    local_drone_ip: '192.168.42.87'
    beswarm_config:
      javanode: operationaltest.ratsflight.pingpong.twobebophover.BebopOneHover
      nodename: BeSwarm
      rosparam:
        drone_name: drone_two
        takeoff_time_in_secs: 10.0
        start_flying_time_in_secs: 20.0

synchronizer:
  ros_master_port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}
