time_sync_topic: ${time_sync_topic}
fused_pose_topic: ${fused_pose_topic}
marker_pose_topic: ${marker_pose_topic}
virtual_environment_topic: ${virtual_environment_topic}

ros_driver_drone_name: bebop

control_frequency_in_hz: 20.0
pid_lag_time_in_seconds: 1.0

pid_velocity_x_kp: 0.2
pid_velocity_x_kd: 0.8

pid_velocity_y_kp: 0.2
pid_velocity_y_kd: 0.8

pid_velocity_z_kp: 0.8
pid_velocity_z_kd: 0.2

pid_velocity_yaw_kp: 0.3

pid_acceleration_x_kp: 0.5
pid_acceleration_y_kp: 0.5