launch_components:
  bebop_autonomy: true
  point_camera_downward: false
  record_rosbag: true
  launch_xbox_controller: true
  launch_arlocros: true
  launch_beswarm: true

bebops:
  Nerve:
    ros_master_port: '11311'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.62.1'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.CircleOT
      nodename: BeSwarmNerve
    rosparam:
      drone_name: Nerve
      unique_integer_id: 1
      takeoff_time_in_secs: 5.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 36
      center_x: 3.0
      center_y: 0.0
      center_z: 1.5
      yaw: -3.14
      radius: 1.0
      frequency: 0.075
      phase: 0.0
      duration: 60.0
    number_of_arlocros: 3

synchronizer:
  ros_master_port: '11316'
  sync_config: master_sync.yaml
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}

pose_aggregation:
  ros_master_port: '11317'
  sync_config: pose_sync.yaml
