#markerpattern 4x6
marker_size: 0.2885

relative_corner_position:
  upper_left: [0, 0, 0]
  upper_right: [0, 0, 1]
  lower_right: [0, -1, 1]
  lower_left: [0, -1, 0]

markers:
  4x4_1.patt: [4, 1, 2]
  4x4_2.patt: [4, 0, 2]
  4x4_3.patt: [4, -1, 2]
  4x4_4.patt: [4, -2, 2]
  4x4_5.patt: [4, -3, 2]
  4x4_6.patt: [4, -4, 2]
  4x4_9.patt: [4, 0.91, 1]
  4x4_10.patt: [4, -0.09, 1]
  4x4_11.patt: [4, -1.09, 1]
  4x4_12.patt: [4, -2.09, 1]
  4x4_13.patt: [4, -3.09, 1]
  4x4_14.patt: [4, -4.09, 1]
  4x4_17.patt: [4, -7, 1]