launch_components:
  bebop_autonomy: true
  point_camera_downward: true
  record_rosbag: true
  launch_xbox_controller: true
  launch_arlocros: true
  launch_beswarm: false

bebops:
  Nerve:
    ros_master_port: '11311'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.102'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.pingpong.samecircle.BebopOneSameFastCircle
      nodename: BeSwarmFake
    rosparam:
      unique_integer_id: 2
      takeoff_time_in_secs: 5.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 36

synchronizer:
  ros_master_port: '11313'
  sync_config: master_sync.yaml
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}