launch_components:
  bebop_autonomy: true
  point_camera_downward: false
  record_rosbag: true
  launch_xbox_controller: true
  launch_arlocros: true
  launch_beswarm: true

bebops:
  Nerve:
    ros_master_port: '11311'
    bebop_ip: '192.168.32.1'
    local_drone_ip: '192.168.32.23'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.pingpong.circle.BebopOneCircle
      nodename: BeSwarmNerve
      rosparam:
        unique_integer_id: 1
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  Romeo:
    ros_master_port: '11312'
    bebop_ip: '192.168.42.1'
    local_drone_ip: '192.168.42.87'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.pingpong.circle.BebopTwoCircle
      nodename: BeSwarmRomeo
      rosparam:
        unique_integer_id: 2
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  ros_master_port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}
