launch_components:
  bebop_autonomy: true
  point_camera_downward: false
  record_rosbag: false
  launch_xbox_controller: true
  launch_arlocros: true
  launch_beswarm: true

bebops:
  D1:
    ros_master_port: '11311'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.0.191'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.bebop.rats.BebopFlyStraightLine
      nodename: BeSwarmD1
    rosparam:
      drone_name: D1
      unique_integer_id: 1
      takeoff_time_in_secs: 5.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 36
      start_pose: '[2.0,1.0,1.5,-3.14]'
      end_pose: '[3.0,-1.5,1.5,-3.14]'
      velocity: 3.0
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land
      /virt_env: ${virtual_environment_topic}
    number_of_arlocros: 3

  D2:
    ros_master_port: '11312'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.0.190'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.applications.parrot.bebop.rats.BebopFlyStraightLine
      nodename: BeSwarmD2
    rosparam:
      drone_name: D2
      unique_integer_id: 2
      takeoff_time_in_secs: 5.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 40
      start_pose: '[4.0,-4.0,1.5,-3.14]'
      end_pose: '[3.0,-1.5,1.5,-3.14]'
      velocity: 3.0
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land
      /virt_env: ${virtual_environment_topic}
    number_of_arlocros: 3

synchronizer:
  ros_master_port: '11316'
  sync_config: master_sync.yaml
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}