bebops:
  bebop_one:
    port: '11311'
    bebop_ip: '192.168.32.1'
    local_drone_ip: '192.168.32.23'
    master_sync_config_file: ${config_dir}/master_sync.yaml
    arlocros_config_file: ${config_dir}/arlocros.yaml
    beswarm_config:
      beswarm_config_file: ${config_dir}/beswarm.yaml
      javanode: applications.parrot.bebop.rats.BebopOne
      nodename: BeSwarmOne
      rosparam:
        ros_driver_drone_name: bebop
        drone_name: drone_one
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  bebop_two:
    port: '11312'
    bebop_ip: '192.168.42.1'
    local_drone_ip: '192.168.42.87'
    master_sync_config_file: ${config_dir}/master_sync.yaml
    arlocros_config_file: ${config_dir}/arlocros.yaml
    beswarm_config:
      beswarm_config_file: ${config_dir}/beswarm.yaml
      javanode: applications.parrot.bebop.rats.BebopTwo
      nodename: BeSwarmTwo
      rosparam:
        ros_driver_drone_name: bebop
        drone_name: drone_two
        takeoff_time_in_secs: 10.0
        start_flying_time_in_secs: 20.0

synchronizer:
  port: '11313'
  master_sync_config_file: ${config_dir}/master_sync.yaml
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}