bebop_one:
  port: '11311'
  bebop_ip: '192.168.32.1'
  local_drone_ip: '192.168.32.23'
  master_sync_config_file: ${abs_path}/master_sync.yaml
  arlocros_config_file: ${abs_path}/arlocros.yaml
  beswarm_config_file: ${abs_path}/beswarm.yaml
  javanode: applications.parrot.bebop.rats.BebopOne
  drone_name: bebop_one
  takeoff_time_in_secs: 5
  start_flying_time_in_secs: 10

bebop_two:
  port: '11312'
  bebop_ip: '192.168.42.1'
  local_drone_ip: '192.168.42.87'
  master_sync_config_file: ${abs_path}/master_sync.yaml
  arlocros_config_file: ${abs_path}/arlocros.yaml
  beswarm_config_file: ${abs_path}/beswarm.yaml
  javanode: applications.parrot.bebop.rats.BebopTwo
  drone_name: bebop_two
  takeoff_time_in_secs: 10
  start_flying_time_in_secs: 20
