launch_components:
  bebop_autonomy: true
  point_camera_downward: false
  record_rosbag: true
  launch_xbox_controller: true
  launch_arlocros: true
  launch_beswarm: true

bebops:
  bebop_one:
    port: '11311'
    bebop_ip: '192.168.32.1'
    local_drone_ip: '192.168.32.23'
    beswarm_config:
      javanode: operationaltesting.ratsflight.BebopOneCircle
      nodename: BeSwarmOne
      rosparam:
        ros_driver_drone_name: bebop
        drone_name: drone_one
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

  bebop_two:
    port: '11312'
    bebop_ip: '192.168.42.1'
    local_drone_ip: '192.168.42.87'
    beswarm_config:
      javanode: operationaltesting.ratsflight.BebopTwoCircle
      nodename: BeSwarmTwo
      rosparam:
        ros_driver_drone_name: bebop
        drone_name: drone_two
        takeoff_time_in_secs: 5.0
        start_flying_time_in_secs: 10.0

synchronizer:
  port: '11313'
  python_node: Synchronizer.py
  rosparam:
    time_sync_topic: ${time_sync_topic}
