launch_components:
  bebop_autonomy: true
  point_camera_downward: true
  record_rosbag: false
  launch_xbox_controller: false
  launch_arlocros: true
  launch_beswarm: true
  common_takeoff_land: true

bebops:
  Nerve:
    ros_master_port: '11311'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.170'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.theater.swarmview.NerveSwarmView
      nodename: BeSwarmNerve
    rosparam:
      drone_name: Nerve
      unique_integer_id: 1
      takeoff_time_in_secs: 5.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 36
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land

  Romeo:
    ros_master_port: '11312'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.120'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.theater.swarmview.RomeoSwarmView
      nodename: BeSwarmRomeo
    rosparam:
      drone_name: Romeo
      unique_integer_id: 2
      takeoff_time_in_secs: 105.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 40
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land

  Juliet:
    ros_master_port: '11313'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.110'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.theater.swarmview.JulietSwarmView
      nodename: BeSwarmJuliet
    rosparam:
      drone_name: Juliet
      unique_integer_id: 3
      takeoff_time_in_secs: 105.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 44
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land

  Fievel:
    ros_master_port: '11314'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.160'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.theater.swarmview.FievelSwarmView
      nodename: BeSwarmFievel
    rosparam:
      drone_name: Fievel
      unique_integer_id: 4
      takeoff_time_in_secs: 74.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 48
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land

  Dumbo:
    ros_master_port: '11315'
    sync_config: master_sync.yaml
    bebop_ip: '192.168.13.180'
    beswarm_config:
      javanode: io.github.hoangtungdinh.beswarm.operationaltest.ratsflight.theater.swarmview.DumboSwarmView
      nodename: BeSwarmDumbo
    rosparam:
      drone_name: Dumbo
      unique_integer_id: 5
      takeoff_time_in_secs: 165.0
      start_flying_time_in_secs: 10.0
      bebop/bebop_driver/NetworkSettingsWifiSelectionChannel: 48
    topic_relay:
      ${common_takeoff_topic}: /bebop/takeoff
      ${common_land_topic}: /bebop/land

#synchronizer:
#  ros_master_port: '11316'
#  sync_config: master_sync.yaml
#  python_node: Synchronizer.py
#  rosparam:
#    time_sync_topic: ${time_sync_topic}

#pose_aggregation:
#  ros_master_port: '11317'
#  sync_config: pose_sync.yaml

